language: cpp

install:
  # Pip cannot install Conan without these upgrades
  - python3 -m pip install --upgrade pip setuptools
  # Install Conan and CMake >= 3.15
  - python3 -m pip install conan cmake

  # Fail if we can't run Conan.
  - conan --version

jobs:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode11.2    # includes gcc-9 by default
      addons: {
        homebrew:{ packages:
                     ['doxygen',
                      'python3-pip',
                      'gcc9',
                      'cppcheck',
                      'ccache']
          }
      }
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      addons: {
        homebrew: { packages:
                      [ 'doxygen',
                        'python3-pip',
                        'gcc9',
                        'cppcheck',
                        'ccache' ]
        }
      }
      env:
        - MATRIX_EVAL=""
    - os: linux
      dist: bionic
      compiler: gcc
      addons: {
        apt: { packages:
                      [ 'doxygen',
                        'python3-pip',
                        'gcc9',
                        'cppcheck',
                        'ccache' ]
        }
      }
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons: {
        homebrew: { packages:
                      [ 'doxygen',
                        'python3-pip',
                        'gcc9',
                        'cppcheck',
                        'ccache' ]
        }
      }



before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -S . -B ./build -D ENABLE_COVERAGE:BOOL=ON ../
  - cmake --build ./build -- -j2
  - cd build && ctest -j2



